chore: update dependencies for Angular 15
ngneat/hot-toast pull request #116
Opened 2022-11-25 16:41 UTC by luishcastroc

- Update dependencies for Angular 15
- Update Cypress to 11
- Update Husky to 8
- Updated dependencies
- Fixed issue #113 

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

Dependencies were updated for latest Angular,Cypress and Husky.

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[x] Other... Please describe: Updated dependencies for latest Angular 15
```

## What is the current behavior?

#113 

Issue Number: #113 

## What is the new behavior?

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

## Other information

2022-12-05 16:20 UTC, shhdharmen requested changes
This PR should be breaking change. Please follow below steps:

1. Change target branch to `beta`, so that testing can be done
2. Push a commit by selecting breaking change

2022-12-05 16:20 UTC, shhdharmen commented on cypress/e2e/toast_events.cy.ts
> -    cy.get('@eventsToast').should('be.visible');
Is this change needed?

2022-12-05 16:20 UTC, shhdharmen commented on projects/ngneat/hot-toast/src/lib/components/hot-toast/hot-toast.component.ts
> +  encapsulation: ViewEncapsulation.None,
Why is this needed?

2022-12-05 16:22 UTC, luishcastroc commented on cypress/e2e/toast_events.cy.ts
> -    cy.get('@eventsToast').should('be.visible');
for some reason cypress is not considering the toast as visible even when is there, it may be a cypress issue but checking the css i was not able to find anything and the cypress debug says is not visible.

2022-12-05 16:25 UTC, luishcastroc commented on projects/ngneat/hot-toast/src/lib/components/hot-toast/hot-toast.component.ts
> +  encapsulation: ViewEncapsulation.None,
the keyframes that animate the toast are the ones generating the issue that avoids the toast to be dismissed in Angular 15 applications as per this documentation from Angular [Angular Keyframes Changes Angular 15](https://angular.io/guide/update-to-version-15)

2022-12-06 05:17 UTC, pascalmann commented on projects/ngneat/hot-toast/src/lib/components/hot-toast/hot-toast.component.ts
> +  encapsulation: ViewEncapsulation.None,
It would be better to prefix the keyframes names with the component selector in `toastBarBaseStyles()` and `close()` methods (`projects/ngneat/hot-toast/src/lib/components/hot-toast/hot-toast.component.ts`).

ex: 
```
const enterAnimation = `hot-toast_hotToastEnterAnimation${
    top ? 'Negative' : 'Positive'
} ${ENTER_ANIMATION_DURATION}ms cubic-bezier(0.21, 1.02, 0.73, 1) forwards`;
```

2022-12-06 05:44 UTC, shhdharmen commented on projects/ngneat/hot-toast/src/lib/components/hot-toast/hot-toast.component.ts
> +  encapsulation: ViewEncapsulation.None,
Correct, please make relevant changes. We can't do `ViewEncapsulation.None`, otherwise dynamic component styles will be affected.

2022-12-06 05:45 UTC, shhdharmen commented on cypress/e2e/toast_events.cy.ts
> -    cy.get('@eventsToast').should('be.visible');
This line can not be removed. Please try to debug more.

2022-12-06 17:43 UTC, luishcastroc commented on projects/ngneat/hot-toast/src/lib/components/hot-toast/hot-toast.component.ts
> +  encapsulation: ViewEncapsulation.None,
i'm checking that option however the generated keyframes doesn't seem to be with the selector.

by inspecting the element i got ng elements ex. **_ngcontent-vkc-c15_hotToastEnterAnimationNegative**

2022-12-07 00:59 UTC, luishcastroc commented on projects/ngneat/hot-toast/src/lib/components/hot-toast/hot-toast.component.ts
> +  encapsulation: ViewEncapsulation.None,
after some research I made it work but not sure if is the best solution.

```typescript
  private hostId: string;

  private unlisteners: VoidFunction[] = [];

  constructor(
    private injector: Injector,
    private renderer: Renderer2,
    private ngZone: NgZone,
    @Inject(APP_ID) appId: string
  ) {
    this.hostId = `_ngcontent-${appId}-${this.constructor['ɵcmp'].id}`;
  }
```

I ended up adding the app_id so I can generate the hostId and then attach it to the animations as recommended.

```typescript
get toastBarBaseStyles() {
    if (this.toastBarBase) {
      const { nativeElement } = this.toastBarBase;
      console.log(nativeElement);
      const top = this.toast.position.includes('top');

      const enterAnimation = `${this.hostId}_hotToastEnterAnimation${
        top ? 'Negative' : 'Positive'
      } ${ENTER_ANIMATION_DURATION}ms cubic-bezier(0.21, 1.02, 0.73, 1) forwards`;

      const exitAnimation = `${this.hostId}_hotToastExitAnimation${
        top ? 'Negative' : 'Positive'
      } ${EXIT_ANIMATION_DURATION}ms forwards cubic-bezier(0.06, 0.71, 0.55, 1) ${this.toast.duration}ms`;

      const animation = this.toast.autoClose ? `${enterAnimation}, ${exitAnimation}` : enterAnimation;

      return { ...this.toast.style, animation };
    }
  }
```

not sending this change until I know if that may be a good solution.

2022-12-07 03:51 UTC, shhdharmen commented on projects/ngneat/hot-toast/src/lib/components/hot-toast/hot-toast.component.ts
> +  encapsulation: ViewEncapsulation.None,
I think it's better to move all css in a global style and avoid complex names of keyframes.

1. Create a styles.scss and move all components styles code there
2. Make changes in `ng add` command so that library's styles.scss is added in consumer project's `angular.json`.

2022-12-07 05:43 UTC, pascalmann commented on projects/ngneat/hot-toast/src/lib/components/hot-toast/hot-toast.component.ts
> +  encapsulation: ViewEncapsulation.None,
The library should stay standalone and not depend on global styles.

A solution would be to get the scope from the component class like this. (using the `nativeElement` extracted from `this.toasBarBase`):
https://stackblitz.com/edit/angular-ivy-bqz9xm?file=src%2Fapp%2Fhello.component.ts

2022-12-07 06:45 UTC, pascalmann commented on projects/ngneat/hot-toast/src/lib/components/hot-toast/hot-toast.component.ts
> +  encapsulation: ViewEncapsulation.None,
For backward compatibility, the keyframes variables must be conditionnally declared with angular major version:
https://angular.io/api/core/Version

2022-12-07 11:09 UTC, pascalmann commented on projects/ngneat/hot-toast/src/lib/components/hot-toast/hot-toast.component.ts
> +  encapsulation: ViewEncapsulation.None,
@shhdharmen Yes but you will loose the scoped styles of the component.

2022-12-07 11:31 UTC, shhdharmen commented on projects/ngneat/hot-toast/src/lib/components/hot-toast/hot-toast.component.ts
> +  encapsulation: ViewEncapsulation.None,
Why do we need scoped styles? Using None encapsulation will introduce many other issues. For example, consumer's global styles will stop working.

2022-12-07 13:33 UTC, luishcastroc commented on projects/ngneat/hot-toast/src/lib/components/hot-toast/hot-toast.component.ts
> +  encapsulation: ViewEncapsulation.None,
> The library should stay standalone and not depend on global styles.
> 
> 
> 
> A solution would be to get the scope from the component class like this:
> 
> https://stackblitz.com/edit/angular-ivy-bqz9xm?file=src%2Fapp%2Fhello.component.ts

Precisely the solution I put is doing this, is just generating it inside the constructor, so do you suggest to use this function instead? I think the results are the same since the id is generated with _ngcontent-appid-scopeid and that's what I generated inside the constructor

2022-12-07 14:07 UTC, shhdharmen commented on projects/ngneat/hot-toast/src/lib/components/hot-toast/hot-toast.component.ts
> +  encapsulation: ViewEncapsulation.None,
I suggest to not make any changes in component's code for styling and simply move styles at global level.

What you have done is not easy to understand and maintain. While simple global styles are readable and easy to understand. And anyone can change if needed due to its simplicity.

2022-12-08 00:01 UTC, luishcastroc commented on projects/ngneat/hot-toast/src/lib/components/hot-toast/hot-toast.component.ts
> +  encapsulation: ViewEncapsulation.None,
@shhdharmen i changed the styles on the last commit however I may need a little help on the ng-add since I have no experience with schematics

2022-12-08 13:14 UTC, shhdharmen commented on projects/ngneat/hot-toast/src/lib/components/hot-toast/hot-toast.component.ts
> +  encapsulation: ViewEncapsulation.None,
I suggest following changes:

1. Create `src/lib/styles` folder
2. Create style file for each component from `src/lib/components` folder into `src/lib/styles/components` folder
3. Create `src/lib/styles/styles.scss` and import all of above files into it
4. Make sure that when lib is build, it generates `styles.css` file separately

2022-12-09 15:34 UTC, luishcastroc commented on projects/ngneat/hot-toast/src/lib/components/hot-toast/hot-toast.component.ts
> +  encapsulation: ViewEncapsulation.None,
please let me know if the changes are good or if I'm missing anything.

2022-12-11 05:47 UTC, shhdharmen requested changes
Please check my comments. Also make sure that when project is built, styles file is `styles.css` and not `styles.scss`.

2022-12-11 05:47 UTC, shhdharmen commented on CHANGELOG.md
> +# [4.2.0-beta.1](https://github.com/ngneat/hot-toast/compare/v4.1.1...v4.2.0-beta.1) (2022-12-05)
Please revert changes of this file

2022-12-11 05:47 UTC, shhdharmen commented on projects/ngneat/hot-toast/ng-package.json
> +  "assets": ["src/styles.scss", "src/styles/components/*"]
COmponents' styles should be imported in styles.scss, they should not be exported as separate assets,

2022-12-11 05:47 UTC, shhdharmen commented on projects/ngneat/hot-toast/schematics/ng-add/index.ts
> +const stylesPath = `./node_modules/@ngneat/hot-toast/src/styles.scss`;
You will need to find path to style file, can't use absolute path.

2022-12-11 05:47 UTC, shhdharmen commented on projects/ngneat/hot-toast/src/lib/components/hot-toast/hot-toast.component.ts
> +  ViewEncapsulation,
Removed unused.

2022-12-11 05:47 UTC, shhdharmen commented on projects/ngneat/hot-toast/src/styles/components/_index.scss
> +@use 'animated-icon';
use `@forward` for all files.

2022-12-11 13:04 UTC, luishcastroc commented on projects/ngneat/hot-toast/schematics/ng-add/index.ts
> +const stylesPath = `./node_modules/@ngneat/hot-toast/src/styles.scss`;
but this is the one it comes from the library? won't be always the same? or supposed to be the same?

2022-12-11 13:16 UTC, shhdharmen commented on projects/ngneat/hot-toast/schematics/ng-add/index.ts
> +const stylesPath = `./node_modules/@ngneat/hot-toast/src/styles.scss`;
You are right, I can't think of scenario when it will be different. And I think `angular.json` will always be at same path from `node_modules`.

2022-12-11 14:54 UTC, luishcastroc commented on projects/ngneat/hot-toast/ng-package.json
> +  "assets": ["src/styles.scss", "src/styles/components/*"]
the library needs to export the parents as well so the main style css can forward them, otherwise the style.scss only ends up with ```sass @use 'styles/components'; ``` and it won't import the others.

2022-12-11 14:56 UTC, luishcastroc commented on CHANGELOG.md
> +# [4.2.0-beta.1](https://github.com/ngneat/hot-toast/compare/v4.1.1...v4.2.0-beta.1) (2022-12-05)
done

2022-12-11 14:56 UTC, luishcastroc commented on projects/ngneat/hot-toast/src/styles/components/_index.scss
> +@use 'animated-icon';
done

2022-12-11 15:11 UTC, luishcastroc commented on projects/ngneat/hot-toast/schematics/ng-add/index.ts
> +const stylesPath = `./node_modules/@ngneat/hot-toast/src/styles.scss`;
are we good to close this one?

2022-12-12 00:11 UTC, luishcastroc commented
> Please check my comments. Also make sure that when project is built, styles file is `styles.css` and not `styles.scss`.

if the project is using scss why do we need to generate a css? not sure I follow in this one

2022-12-12 04:51 UTC, shhdharmen commented
> > Please check my comments. Also make sure that when project is built, styles file is `styles.css` and not `styles.scss`.
> 
> if the project is using scss why do we need to generate a css? not sure I follow in this one

I understand your point, but you will need to check 1 scenario.

What if client's project is not using scss? Consider that client's main styles file is `styles.css`, so the `angular.json` will become like below, will it work?

```json
{
    "styles": ["styles.css", "path/to/hot-toast/styles.scss"]
}
```

2022-12-12 05:39 UTC, shhdharmen commented on projects/ngneat/hot-toast/schematics/ng-add/index.ts
> +const stylesPath = `./node_modules/@ngneat/hot-toast/src/styles.scss`;
Few changes are needed, you will need to conditionally check for `css` and `scss`:

1. If client's project is using `css`, then our library's style file in `css` format should be added in `angular.json`
2. If client's project is using `scss`, then import our library's style file in `scss` format in their main style file using `@use`

2022-12-17 01:36 UTC, luishcastroc commented on projects/ngneat/hot-toast/ng-package.json
> +  "assets": ["src/styles.scss", "src/styles/components/*"]
changes done

2022-12-17 01:36 UTC, luishcastroc commented on projects/ngneat/hot-toast/schematics/ng-add/index.ts
> +const stylesPath = `./node_modules/@ngneat/hot-toast/src/styles.scss`;
this is completed

2022-12-26 13:51 UTC, luishcastroc commented on projects/ngneat/hot-toast/src/lib/components/hot-toast/hot-toast.component.ts
> +  encapsulation: ViewEncapsulation.None,
Hi, last changes sent is there anything else we should check in this?

2023-01-03 10:51 UTC, shhdharmen requested changes
LGTM. Please revert changes of CHANGELOG.

2023-01-03 10:51 UTC, shhdharmen commented on CHANGELOG.md
>  # [4.1.0](https://github.com/ngneat/hot-toast/compare/v4.0.1...v4.1.0) (2021-12-27)
Revert changes of this file.

2023-01-03 12:33 UTC, luishcastroc commented on CHANGELOG.md
>  # [4.1.0](https://github.com/ngneat/hot-toast/compare/v4.0.1...v4.1.0) (2021-12-27)
hi not sure what I need to revert here? I copied the entire file from the master and is not reflecting any change.

2023-01-06 06:04 UTC, shhdharmen approved these changes

2023-01-06 06:28 UTC, merged