docs(readme.md): update styles reference for version 5
ngneat/hot-toast pull request #119
Opened 2023-01-10 14:06 UTC by luishcastroc

add docuentation with the steps to add styles when using version 5 (Angular 15>=)

113

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

REAME is missing the description of how to add styles when using version 5

Issue Number: N/A

## What is the new behavior?

README now includes a description on how to add styles to your project.

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

## Other information

2023-01-11 10:26 UTC, shhdharmen requested changes

2023-01-11 10:26 UTC, shhdharmen commented on README.md
> +## For Angular version >= 15
Add this section inside braking changes section.

2023-01-11 10:26 UTC, shhdharmen commented on README.md
> +For this verion you will also need to import the styles from the library like this
User does not need to do anything. It's already taken care through `ng add ...`. So mention it like that.

2023-01-11 14:12 UTC, luishcastroc commented on README.md
> +## For Angular version >= 15
should i remove it from here and just add it there? or keep it with the manual explanation in here as well?

2023-01-11 17:01 UTC, shhdharmen commented on README.md
> +## For Angular version >= 15
Yes, just keep it under breaking changes.

2023-01-13 13:25 UTC, luishcastroc commented on README.md
> +## For Angular version >= 15
this is completed, should we as well put the proper release? today reflects 4.1.0 but if I install from npm using latest it will get the 5.0.0

2023-01-16 09:53 UTC, shhdharmen approved these changes

2023-01-16 09:54 UTC, merged

2023-01-21 06:58 UTC, shhdharmen commented
:tada: This PR is included in version 5.0.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@ngneat/hot-toast/v/5.0.1)
- [GitHub release](https://github.com/ngneat/hot-toast/releases/tag/v5.0.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: