feat: add forFeature configuration
ngneat/hot-toast pull request #131
Opened 2023-06-28 20:43 UTC by va-stefanek

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: 104

## What is the new behavior?

Allow to setup hot-toast for dedicated with dedicated configuration

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

2023-06-29 00:41 UTC, shhdharmen requested changes

2023-06-29 00:41 UTC, shhdharmen commented on projects/ngneat/hot-toast/src/lib/hot-toast.module.ts
> +      providers: [{ provide: ToastConfig, useValue: config }, HotToastService],
HotToastService is already provided in root.

2023-06-29 06:59 UTC, va-stefanek commented on projects/ngneat/hot-toast/src/lib/hot-toast.module.ts
> +      providers: [{ provide: ToastConfig, useValue: config }, HotToastService],
Yea I will change it, that  there will be possibly multiple instances of HotToastService. I revert it by mistake sorry

2023-07-01 07:20 UTC, shhdharmen commented
Please add relevant information in README and also add test cases.

2023-07-01 07:20 UTC, shhdharmen requested changes
Please add relevant information in README and also add test cases.

2023-07-04 06:38 UTC, shhdharmen reviewed
Add test cases

2023-07-04 10:22 UTC, shhdharmen commented
@va-stefanek yeah, add a feature module in demo app and test it with Cypress.

2023-07-08 15:23 UTC, shhdharmen requested changes

2023-07-08 15:23 UTC, shhdharmen commented on src/app/app.module.ts
> +  imports: [BrowserModule, BrowserAnimationsModule, SharedModule, HotToastModule.forRoot({}), RouterModule, RouterModule.forRoot(routes)],
Imported `RouterModule` twice.

2023-07-25 15:22 UTC, shhdharmen approved these changes

2023-08-26 21:01 UTC, va-stefanek commented
@shhdharmen done

2023-09-04 10:37 UTC, merged

2023-09-04 11:06 UTC, shhdharmen commented
@va-stefanek `forFeature` is not working as expected for non-lazy loaded modules.