feat: Add button to trigger callback action
ngneat/hot-toast pull request #135
Opened 2023-08-16 15:45 UTC by johnfewell

Adds a new feature enabling an optional action button to be added to toast messages. This action button can be customized with a label and a callback function, providing additional user interaction possibilities. It also adds an optional style input to style the action button.

✅ Closes: 8

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

Updated the Toast interface to include an optional action property. This property is an object consisting of a label (the text to be displayed on the button) and a callback (the function to be executed when the action button is clicked).

Modified the createToast method in our HotToastService to accept and handle the new action property.

Added a new `executeAction` method in the HotToastComponent that triggers the callback function and closes the toast.

Updated the HotToastComponent template to conditionally render the action button based on the presence of the action property.

Introduced new custom CSS properties for easy theming of the action button.

Added test coverage to ensure that the action button functions as expected, including a check that the callback function is executed when the action button is clicked.

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

There is no option to easily execute callback functions from a toast.  

Issue Number: 8

## What is the new behavior?

There is an optional action property that can be configured to trigger a callback when the user clicks the action button in the toast. 

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

## Other information

This new feature enhances the interactivity of our toast notifications, allowing us to provide users with actionable options directly within the notifications themselves.

2023-09-04 10:36 UTC, shhdharmen approved these changes

2023-09-04 11:18 UTC, shhdharmen commented
@johnfewell please change target branch to beta.

2023-09-04 18:58 UTC, johnfewell commented
> @johnfewell please change target branch to beta.

@shhdharmen Done.

2023-09-18 13:02 UTC, johnfewell commented
@shhdharmen No merge, just closed?

2023-09-18 13:07 UTC, shhdharmen requested changes

2023-09-18 13:07 UTC, shhdharmen commented on projects/ngneat/hot-toast/src/lib/hot-toast.service.ts
> +        action: options?.action,
I don't this line is needed. Taken care in `...options`.

2023-09-18 13:15 UTC, shhdharmen commented
![image](https://github.com/ngneat/hot-toast/assets/6831283/be460dc9-6d25-4acb-bb14-95f737217a0f)
 
- Check alignment
- remove font style from action button

2023-10-10 08:37 UTC, closed without merging