feat: upgrade to Angular 16, mark components as standalone
ngneat/hot-toast pull request #136
Opened 2023-08-22 21:54 UTC by arturovt

This commit upgrades the workspace to Angular 16, as it includes security fixes necessary to ensure compatibility with content security policies. All components have been designated as `standalone`, eliminating the need for them to be declared within the `HotToastModule`. Consequently, `HotToastModule` is now deprecated, as it is unnecessary for standalone applications.

2023-08-25 09:46 UTC, arturovt commented
@shhdharmen friendly ping.

2023-08-29 16:29 UTC, arturovt commented
@NetanelBasal friendly ping.

2023-08-30 06:55 UTC, shhdharmen commented
I will review it this weekend.

2023-09-04 11:16 UTC, shhdharmen requested changes
- Convert docs application to standalone
- Make sure to have cypress test cases for standard and standalone, both
- Add example in docs app to showcase how to use the library with standalone component
- Change target branch to beta

2023-09-04 11:16 UTC, shhdharmen commented on projects/ngneat/hot-toast/schematics/ng-add/utils/index.ts
> +  const project = workspace.projects[projectName!];
Why removed default project?

2023-09-04 11:16 UTC, shhdharmen commented on projects/ngneat/hot-toast/src/lib/hot-toast.module.ts
> + * @deprecated Use `provideHotToastConfig` to provide a global toast configuration.
We don't want to deprecate usage of modules.

2023-09-18 11:20 UTC, merged

2023-09-18 11:50 UTC, shhdharmen commented
:tada: This PR is included in version 6.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@ngneat/hot-toast/v/6.0.0)
- [GitHub release](https://github.com/ngneat/hot-toast/releases/tag/v6.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: