fix: add ability to pass attributes to hot-toast
ngneat/hot-toast pull request #78
Opened 2021-07-28 13:22 UTC by gili-lumigo

## PR Checklist

Please check if your PR fulfills the following requirements:

- [V] The commit message follows our guidelines: CONTRIBUTING.md#commit
- [V] Tests for the changes have been added (for bug fixes / features)
- [V] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ V] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

hot-toast doesn't support passing attributes as part of the ToastOptions

Issue Number: N/A

## What is the new behavior?

hot-toast does support passing attributes as part of the ToastOptions

## Does this PR introduce a breaking change?

```
[ ] Yes
[V] No
```

## Other information

2021-07-30 07:47 UTC, shhdharmen commented
The commit message should have `feat:` in it.

2021-07-30 07:59 UTC, shhdharmen requested changes

2021-07-30 07:59 UTC, shhdharmen commented on projects/ngneat/hot-toast/src/lib/components/hot-toast/hot-toast.component.ts
> +    if (toastAttributes) {
Can we give default value `{}` to attributes? So that we can avoid this check.

2021-07-30 07:59 UTC, shhdharmen commented on README.md
> +| attributes  | [`Record<string, string>`](https://www.typescriptlang.org/docs/handbook/utility-types.html#recordkeystype)
There is one extra column in this.

2021-07-30 08:00 UTC, shhdharmen commented
What is motivation for this? What extra attributes you want pass in the toast?

2021-07-30 10:26 UTC, gili-lumigo commented on projects/ngneat/hot-toast/src/lib/components/hot-toast/hot-toast.component.ts
> +    if (toastAttributes) {
Sure, Ill add it to the defaultConfig

2021-07-30 10:28 UTC, gili-lumigo commented on README.md
> +| attributes  | [`Record<string, string>`](https://www.typescriptlang.org/docs/handbook/utility-types.html#recordkeystype)
Missed it... Fixing it

2021-08-04 18:00 UTC, gili-lumigo commented
@shhdharmen 

The motivation was that I needed to set attributes that I can later query when I'm e2e testing the component.

2021-08-06 07:07 UTC, shhdharmen requested changes
Commit messages are still wrong.

2021-08-06 13:59 UTC, gili-lumigo commented
@shhdharmen 

Fixed all messages

2021-08-07 07:38 UTC, shhdharmen approved these changes
LGTM

2021-08-07 07:39 UTC, shhdharmen commented
You may want to add yourself as contributor. Just run `npm run contributors:add`.

2021-08-07 08:37 UTC, gili-lumigo commented
:)

I've added myself.

2021-08-07 11:19 UTC, merged

2021-08-07 11:21 UTC, shhdharmen commented
:tada: This PR is included in version 3.4.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@ngneat/hot-toast/v/3.4.0)
- [GitHub release](https://github.com/ngneat/hot-toast/releases/tag/v3.4.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: